project:
  type: website

website:
  title: "Sitio web de Manuel Carabias"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

comments: 
  giscus:
    repo: amataste/carabal


